### ISSUE TITLE
no results after all answers have been given

### ISSUE THREAD

**Issue by fcortesjp** [Noam-Alum/lpi_010_160_exam#1]
after I complete the exam (all 80+ questions). the terminal simply closed up on me and I saw no results
also, how different are these questions from the actual exam questions?

**Comment by Noam-Alum** [comment]
> after I complete the exam (all 80+ questions). the terminal simply closed up on me and I saw no results also, how different are these questions from the actual exam questions?

You are using Windows I suppose, this happens because you've (accidentally) pressed enter twice.
Try running the python script from CMD or using an IDE like vscode.

If you cloned the entire repo you can just run this in powershell:
```bash
python3.exe \PATH\TO\lpi.py
```
And you should be good to go :)

---

The last I checked, these are all the questions they may ask.
